/**
 * PPTX Creator Tool — Generate Microsoft PowerPoint presentations from AI.
 *
 * Supports slides with titles, content, bullets, tables, and images.
 */

import PptxGenJS from "pptxgenjs";

export interface PptxSlide {
  /** Slide layout type */
  type: "title" | "titleContent" | "twoColumn" | "sectionHeader" | "blank";
  /** Slide title */
  title?: string;
  /** Slide subtitle (for title slide) */
  subtitle?: string;
  /** Slide content (text or bullets) */
  content?: string[];
  /** Left column content (for twoColumn) */
  leftContent?: string[];
  /** Right column content (for twoColumn) */
  rightContent?: string[];
  /** Background color (hex without #) */
  bgColor?: string;
  /** Text color (hex without #) */
  textColor?: string;
  /** Notes for speaker */
  notes?: string;
}

export interface PptxOptions {
  /** Presentation title */
  title: string;
  /** Presentation author */
  author?: string;
  /** Slides */
  slides: PptxSlide[];
  /** Default background color */
  defaultBgColor?: string;
  /** Default text color */
  defaultTextColor?: string;
  /** Slide size */
  size?: "16:9" | "4:3";
}

const DEFAULT_BG = "1a1a2e";
const DEFAULT_TEXT = "ffffff";
const ACCENT = "0f3460";
const HIGHLIGHT = "e94560";

function hexToHex(color?: string): string {
  if (!color) return DEFAULT_TEXT;
  return color.replace("#", "");
}

/**
 * Create a PowerPoint presentation and return the PptxGenJS instance.
 */
export async function createPptx(options: PptxOptions): Promise<PptxGenJS> {
  const pptx = new PptxGenJS();

  // Set presentation metadata
  pptx.author = options.author || "JARVIS AI OS";
  pptx.title = options.title;
  pptx.subject = `Generated by JARVIS AI OS`;

  // Set slide size
  if (options.size === "4:3") {
    pptx.defineLayout({ name: "CUSTOM", width: 10, height: 7.5 });
    pptx.layout = "CUSTOM";
  }

  const bg = hexToHex(options.defaultBgColor || DEFAULT_BG);
  const text = hexToHex(options.defaultTextColor || DEFAULT_TEXT);

  for (const slide of options.slides) {
    const pptSlide = pptx.addSlide();

    // Background
    pptSlide.background = { color: hexToHex(slide.bgColor || bg) };

    switch (slide.type) {
      case "title":
        // Title slide
        pptSlide.addText(slide.title || "", {
          x: 0.5,
          y: 1.5,
          w: "90%",
          h: 1.5,
          fontSize: 36,
          fontFace: "Arial",
          color: hexToHex(slide.textColor || text),
          bold: true,
          align: "center",
        });
        if (slide.subtitle) {
          pptSlide.addText(slide.subtitle, {
            x: 0.5,
            y: 3.2,
            w: "90%",
            h: 0.8,
            fontSize: 18,
            fontFace: "Arial",
            color: hexToHex(text),
            align: "center",
          });
        }
        break;

      case "titleContent":
        // Title + bullet content
        pptSlide.addText(slide.title || "", {
          x: 0.5,
          y: 0.3,
          w: "90%",
          h: 0.8,
          fontSize: 28,
          fontFace: "Arial",
          color: hexToHex(HIGHLIGHT),
          bold: true,
        });
        if (slide.content && slide.content.length > 0) {
          pptSlide.addText(
            slide.content.map((item) => ({
              text: item,
              options: {
                fontSize: 16,
                fontFace: "Arial",
                color: hexToHex(text),
                bullet: { code: "2022" },
                breakLine: true,
              },
            })),
            {
              x: 0.5,
              y: 1.3,
              w: "90%",
              h: "75%",
              valign: "top",
            }
          );
        }
        break;

      case "twoColumn":
        // Two column layout
        pptSlide.addText(slide.title || "", {
          x: 0.5,
          y: 0.3,
          w: "90%",
          h: 0.8,
          fontSize: 28,
          fontFace: "Arial",
          color: hexToHex(HIGHLIGHT),
          bold: true,
        });
        if (slide.leftContent) {
          pptSlide.addText(
            slide.leftContent.map((item) => ({
              text: item,
              options: {
                fontSize: 14,
                fontFace: "Arial",
                color: hexToHex(text),
                bullet: { code: "2022" },
                breakLine: true,
              },
            })),
            {
              x: 0.5,
              y: 1.3,
              w: "45%",
              h: "75%",
              valign: "top",
            }
          );
        }
        if (slide.rightContent) {
          pptSlide.addText(
            slide.rightContent.map((item) => ({
              text: item,
              options: {
                fontSize: 14,
                fontFace: "Arial",
                color: hexToHex(text),
                bullet: { code: "2022" },
                breakLine: true,
              },
            })),
            {
              x: 52,
              y: 1.3,
              w: "45%",
              h: "75%",
              valign: "top",
            }
          );
        }
        break;

      case "sectionHeader":
        // Section header slide
        pptSlide.addText(slide.title || "", {
          x: 0.5,
          y: 2.5,
          w: "90%",
          h: 1.5,
          fontSize: 32,
          fontFace: "Arial",
          color: hexToHex(HIGHLIGHT),
          bold: true,
          align: "center",
        });
        break;

      case "blank":
        // Blank slide with optional content
        if (slide.content) {
          pptSlide.addText(slide.content.join("\n"), {
            x: 0.5,
            y: 0.5,
            w: "90%",
            h: "90%",
            fontSize: 16,
            fontFace: "Arial",
            color: hexToHex(text),
            valign: "top",
          });
        }
        break;
    }

    // Speaker notes
    if (slide.notes) {
      pptSlide.addNotes(slide.notes);
    }
  }

  return pptx;
}

/**
 * Download a generated PPTX file.
 */
export async function downloadPptx(options: PptxOptions): Promise<void> {
  const pptx = await createPptx(options);
  const filename = `${options.title.replace(/[^a-zA-Z0-9]/g, "_")}.pptx`;
  const buffer = await pptx.write({ outputType: "arraybuffer" });
  const blob = new Blob([buffer as ArrayBuffer], {
    type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  });

  // Dynamic import for file-saver (browser only)
  if (typeof window !== "undefined") {
    const { saveAs } = await import("file-saver");
    saveAs(blob, filename);
  }
}

/**
 * Mastra-compatible tool definition.
 */
export const pptxCreatorTool = {
  name: "createPresentation",
  description:
    "Create a Microsoft PowerPoint presentation (.pptx). Use this when the user asks to " +
    "create a presentation, make slides, generate a PPT, or build a slide deck. " +
    "Returns the file for download.",
  parameters: {
    type: "object" as const,
    properties: {
      title: {
        type: "string",
        description: "Presentation title and filename",
      },
      slides: {
        type: "array",
        description:
          "Array of slides. Each slide has: type (title/titleContent/twoColumn/sectionHeader/blank), " +
          "title, subtitle, content (array of bullet strings), notes.",
        items: {
          type: "object",
          properties: {
            type: { type: "string", enum: ["title", "titleContent", "twoColumn", "sectionHeader", "blank"] },
            title: { type: "string" },
            subtitle: { type: "string" },
            content: { type: "array", items: { type: "string" } },
            leftContent: { type: "array", items: { type: "string" } },
            rightContent: { type: "array", items: { type: "string" } },
            notes: { type: "string" },
            bgColor: { type: "string" },
            textColor: { type: "string" },
          },
          required: ["type"],
        },
      },
    },
    required: ["title", "slides"],
  },
  execute: async (args: PptxOptions) => {
    const pptx = await createPptx(args);
    const filename = `${args.title.replace(/[^a-zA-Z0-9]/g, "_")}.pptx`;
    return {
      success: true,
      filename,
      slideCount: args.slides.length,
      message: `Presentation "${args.title}" with ${args.slides.length} slides created successfully`,
    };
  },
};
