/**
 * Report Creator Tool — Generate structured reports in multiple formats.
 *
 * Supports: project reports, status reports, analysis reports, meeting notes.
 * Output: Markdown, Word (.docx), or HTML.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from "docx";
import { saveAs } from "file-saver";

export interface ReportSection {
  title: string;
  content: string;
  subsections?: ReportSection[];
}

export interface ReportOptions {
  /** Report title */
  title: string;
  /** Report type */
  type: "status" | "project" | "analysis" | "meeting" | "custom";
  /** Author */
  author?: string;
  /** Date */
  date?: string;
  /** Executive summary */
  summary?: string;
  /** Report sections */
  sections: ReportSection[];
  /** Key metrics (name → value) */
  metrics?: Record<string, string | number>;
  /** Recommendations */
  recommendations?: string[];
  /** Output format */
  format?: "markdown" | "docx" | "html";
}

/**
 * Generate a Markdown report.
 */
function generateMarkdown(options: ReportOptions): string {
  const lines: string[] = [];
  const date = options.date || new Date().toLocaleDateString();

  lines.push(`# ${options.title}`);
  lines.push("");
  lines.push(`**Type:** ${options.type.charAt(0).toUpperCase() + options.type.slice(1)} Report`);
  lines.push(`**Author:** ${options.author || "JARVIS AI OS"}`);
  lines.push(`**Date:** ${date}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  if (options.summary) {
    lines.push("## Executive Summary");
    lines.push("");
    lines.push(options.summary);
    lines.push("");
  }

  if (options.metrics && Object.keys(options.metrics).length > 0) {
    lines.push("## Key Metrics");
    lines.push("");
    lines.push("| Metric | Value |");
    lines.push("|--------|-------|");
    for (const [key, value] of Object.entries(options.metrics)) {
      lines.push(`| ${key} | ${value} |`);
    }
    lines.push("");
  }

  for (const section of options.sections) {
    lines.push(`## ${section.title}`);
    lines.push("");
    lines.push(section.content);
    lines.push("");

    if (section.subsections) {
      for (const sub of section.subsections) {
        lines.push(`### ${sub.title}`);
        lines.push("");
        lines.push(sub.content);
        lines.push("");
      }
    }
  }

  if (options.recommendations && options.recommendations.length > 0) {
    lines.push("## Recommendations");
    lines.push("");
    for (const rec of options.recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by JARVIS AI OS*");

  return lines.join("\n");
}

/**
 * Generate an HTML report.
 */
function generateHtml(options: ReportOptions): string {
  const md = generateMarkdown(options);
  // Simple markdown to HTML conversion
  let html = md
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/\| (.+?) \| (.+?) \|/g, "<tr><td>$1</td><td>$2</td></tr>")
    .replace(/---/g, "<hr>")
    .replace(/\n\n/g, "<br><br>");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${options.title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #e94560; padding-bottom: 0.5rem; }
    h2 { color: #0f3460; margin-top: 2rem; }
    h3 { color: #16213e; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    td, th { border: 1px solid #ddd; padding: 0.5rem; text-align: left; }
    th { background: #1a1a2e; color: white; }
    tr:nth-child(even) { background: #f9f9f9; }
    li { margin: 0.25rem 0; }
    hr { border: none; border-top: 1px solid #ddd; margin: 2rem 0; }
    em { color: #666; }
  </style>
</head>
<body>
  ${html}
</body>
</html>`;
}

/**
 * Generate a DOCX report.
 */
async function generateDocx(options: ReportOptions): Promise<Blob> {
  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: options.title, bold: true })],
    })
  );

  // Metadata
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Type: ${options.type.charAt(0).toUpperCase() + options.type.slice(1)} Report | Author: ${options.author || "JARVIS AI OS"} | Date: ${options.date || new Date().toLocaleDateString()}`,
          italics: true,
          color: "666666",
        }),
      ],
    })
  );

  children.push(new Paragraph({ children: [] }));

  // Summary
  if (options.summary) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Executive Summary", bold: true })],
      })
    );
    children.push(
      new Paragraph({
        children: [new TextRun({ text: options.summary })],
      })
    );
  }

    // Metrics table
    if (options.metrics && Object.keys(options.metrics).length > 0) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: "Key Metrics", bold: true })],
        })
      );

      // Simple text-based metrics
      for (const [key, value] of Object.entries(options.metrics)) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `${key}: `, bold: true }),
              new TextRun({ text: String(value) }),
            ],
          })
        );
      }
    }

  // Sections
  for (const section of options.sections) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: section.title, bold: true })],
      })
    );
    children.push(
      new Paragraph({
        children: [new TextRun({ text: section.content })],
      })
    );

    if (section.subsections) {
      for (const sub of section.subsections) {
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_3,
            children: [new TextRun({ text: sub.title, bold: true })],
          })
        );
        children.push(
          new Paragraph({
            children: [new TextRun({ text: sub.content })],
          })
        );
      }
    }
  }

  // Recommendations
  if (options.recommendations && options.recommendations.length > 0) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Recommendations", bold: true })],
      })
    );
    for (const rec of options.recommendations) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: `• ${rec}` })],
          indent: { left: 720 },
        })
      );
    }
  }

  const doc = new Document({
    creator: options.author || "JARVIS AI OS",
    title: options.title,
    sections: [{ children }],
  });

  return await Packer.toBlob(doc);
}

/**
 * Create and download a report.
 */
export async function createReport(options: ReportOptions): Promise<{
  content: string;
  filename: string;
  format: string;
}> {
  const format = options.format || "markdown";
  const safeTitle = options.title.replace(/[^a-zA-Z0-9]/g, "_");

  switch (format) {
    case "markdown": {
      const content = generateMarkdown(options);
      const blob = new Blob([content], { type: "text/markdown" });
      saveAs(blob, `${safeTitle}.md`);
      return { content, filename: `${safeTitle}.md`, format: "markdown" };
    }
    case "html": {
      const content = generateHtml(options);
      const blob = new Blob([content], { type: "text/html" });
      saveAs(blob, `${safeTitle}.html`);
      return { content, filename: `${safeTitle}.html`, format: "html" };
    }
    case "docx": {
      const blob = await generateDocx(options);
      saveAs(blob, `${safeTitle}.docx`);
      return { content: "Report generated as Word document", filename: `${safeTitle}.docx`, format: "docx" };
    }
    default: {
      const content = generateMarkdown(options);
      return { content, filename: `${safeTitle}.md`, format: "markdown" };
    }
  }
}

/**
 * Mastra-compatible tool definition.
 */
export const reportCreatorTool = {
  name: "createReport",
  description:
    "Generate a structured report. Use this when the user asks for a status report, " +
    "project report, analysis report, meeting notes, or any structured document. " +
    "Supports Markdown, Word (.docx), and HTML output formats.",
  parameters: {
    type: "object" as const,
    properties: {
      title: { type: "string", description: "Report title" },
      type: {
        type: "string",
        enum: ["status", "project", "analysis", "meeting", "custom"],
        description: "Type of report",
      },
      summary: { type: "string", description: "Executive summary" },
      sections: {
        type: "array",
        description: "Report sections with title and content",
        items: {
          type: "object",
          properties: {
            title: { type: "string" },
            content: { type: "string" },
            subsections: { type: "array" },
          },
          required: ["title", "content"],
        },
      },
      metrics: {
        type: "object",
        description: "Key metrics as name-value pairs",
      },
      recommendations: {
        type: "array",
        items: { type: "string" },
        description: "List of recommendations",
      },
      format: {
        type: "string",
        enum: ["markdown", "docx", "html"],
        description: "Output format (default: markdown)",
      },
    },
    required: ["title", "type", "sections"],
  },
  execute: async (args: ReportOptions) => {
    const result = await createReport(args);
    return {
      success: true,
      ...result,
      message: `Report "${args.title}" created as ${result.format}`,
    };
  },
};
