import { ClientGig, ServicePackage } from "./types";

/**
 * CURATED HIGH-VALUE CLIENT GIGS ACROSS 8 FREELANCE SERVICE DOMAINS
 */
export const INITIAL_CLIENT_GIGS: ClientGig[] = [
  {
    id: "gig_01",
    title: "Full Stack Next.js 15 & Supabase Web Application for EdTech SaaS",
    clientName: "David K. (Founder)",
    company: "EduSphere Labs",
    platform: "Upwork",
    budget: { amount: 2500, currency: "USD", type: "fixed" },
    category: "website_design",
    description: "Looking for an expert Full Stack Developer to construct a production-ready ed-tech web app with responsive UI, Supabase database auth, vector search, and clean payment integration.",
    requiredSkills: ["Next.js", "React 19", "TypeScript", "Supabase", "Tailwind CSS"],
    postedAt: "2 hours ago",
    clientVerified: true,
    rating: 4.98,
    matchScore: 98,
  },
  {
    id: "gig_02",
    title: "150-Screen Cross-Platform Mobile App UI/UX & Interactive Design",
    clientName: "Elena Rostova",
    company: "GlamourTech Mobile",
    platform: "Wellfound",
    budget: { amount: 1800, currency: "USD", type: "fixed" },
    category: "ui_ux",
    description: "Need a talented UI engineer to develop fluid, responsive mobile interfaces with 3D controls, micro-animations, and Capacitor/React packaging for iOS and Android.",
    requiredSkills: ["React", "Capacitor", "Tailwind CSS", "Mobile UX", "Figma"],
    postedAt: "5 hours ago",
    clientVerified: true,
    rating: 5.0,
    matchScore: 96,
  },
  {
    id: "gig_03",
    title: "Multi-Agent AI Workflow & LLM Tool Calling Pipeline Integration",
    clientName: "Marcus Vance",
    company: "AetherOps AI",
    platform: "Twitter / X",
    budget: { amount: 3500, currency: "USD", type: "fixed" },
    category: "ai_agents",
    description: "We require an AI Engineer to construct an autonomous multi-persona agentic runtime with vector context memory, prompt engineering, and human-in-the-loop safety gates.",
    requiredSkills: ["LLM APIs", "OpenRouter", "Groq", "Agentic Architecture", "TypeScript"],
    postedAt: "1 day ago",
    clientVerified: true,
    rating: 4.95,
    matchScore: 99,
  },
  {
    id: "gig_04",
    title: "Salesforce CRM Bulk Data Entry & Razorpay Donation Reconciliation",
    clientName: "Pooja Sharma (Director)",
    company: "EduCare Foundation",
    platform: "Direct B2B",
    budget: { amount: 1200, currency: "USD", type: "fixed" },
    category: "salesforce_data",
    description: "High-volume data cleaning and reconciliation for 100k+ donation records in Salesforce CRM using Data Loader and Python data validation scripts.",
    requiredSkills: ["Salesforce CRM", "Data Loader", "Excel", "Data Validation", "Python"],
    postedAt: "1 day ago",
    clientVerified: true,
    rating: 5.0,
    matchScore: 97,
  },
  {
    id: "gig_05",
    title: "Python Web Scraping & Automated Data Pipeline to PostgreSQL",
    clientName: "Julian Weber",
    company: "OmniData Analytics",
    platform: "Upwork",
    budget: { amount: 900, currency: "USD", type: "fixed" },
    category: "python_automation",
    description: "Build automated Python scripts to extract, clean, and pipe real-time eCommerce listings into a structured PostgreSQL database with daily cron scheduling.",
    requiredSkills: ["Python", "PostgreSQL", "Automation", "ETL", "BeautifulSoup"],
    postedAt: "2 days ago",
    clientVerified: true,
    rating: 4.9,
    matchScore: 94,
  },
  {
    id: "gig_06",
    title: "Technical SEO Blog Posts & Architecture Walkthrough Articles",
    clientName: "Sarah Lin",
    company: "DevScale Media",
    platform: "LinkedIn",
    budget: { amount: 600, currency: "USD", type: "fixed" },
    category: "content_writing",
    description: "Looking for an experienced software developer to write 4 comprehensive, deeply researched technical blog posts explaining modern AI agent architectures and Next.js 15 SSR.",
    requiredSkills: ["Technical Writing", "Next.js", "AI Architecture", "SEO Optimization"],
    postedAt: "3 days ago",
    clientVerified: true,
    rating: 4.92,
    matchScore: 95,
  },
  {
    id: "gig_07",
    title: "High-Converting 3D Promotional Video Ad for SaaS Launch",
    clientName: "Alexandre Dupuis",
    company: "Vortex App Studio",
    platform: "Upwork",
    budget: { amount: 1100, currency: "USD", type: "fixed" },
    category: "video_ads",
    description: "Create an engaging 45-second product demo video with dynamic screen mockups, viral hook, subtitle animations, and voiceover audio for Instagram & YouTube ads.",
    requiredSkills: ["Video Editing", "Motion Graphics", "Scriptwriting", "Voiceover Sync"],
    postedAt: "3 days ago",
    clientVerified: true,
    rating: 4.88,
    matchScore: 92,
  },
];

/**
 * 8 FREELANCE SERVICE PACKAGES & PRICING
 */
export const SERVICE_PACKAGES: ServicePackage[] = [
  {
    id: "srv_web_design",
    category: "website_design",
    name: "Full Stack Website & SaaS Development",
    description: "Production-grade Next.js 15, React 19, and Supabase responsive web applications with auth, database, and payments.",
    deliverables: ["Custom Responsive UI", "Supabase PostgreSQL Database", "Authentication & Payments", "SEO & Performance Optimization"],
    starterPriceINR: 35000,
    proPriceINR: 75000,
    enterprisePriceINR: 150000,
  },
  {
    id: "srv_ui_ux",
    category: "ui_ux",
    name: "UI/UX & Cross-Platform Mobile App Design",
    description: "Fluid mobile application interfaces with 3D controls, micro-animations, and Capacitor/React runtime packaging.",
    deliverables: ["Figma Design System", "Interactive Prototype", "React/Capacitor Code", "150+ Screen Layouts"],
    starterPriceINR: 25000,
    proPriceINR: 60000,
    enterprisePriceINR: 120000,
  },
  {
    id: "srv_ai_agents",
    category: "ai_agents",
    name: "Autonomous AI Agents & Custom LLM Pipelines",
    description: "Multi-agent systems with tool calling, vector search RAG, Groq/Gemini integration, and safety approval gates.",
    deliverables: ["Multi-Persona Agent Fleet", "Vector Memory Engine", "Tool Calling Integration", "Level 6 Approval Gates"],
    starterPriceINR: 45000,
    proPriceINR: 95000,
    enterprisePriceINR: 200000,
  },
  {
    id: "srv_automation",
    category: "python_automation",
    name: "Python Automation & Workflow ETL Scripts",
    description: "Custom Python bots to eliminate repetitive manual processes, web scraping, and database synchronization.",
    deliverables: ["Automated Python Scripts", "Scheduled Cron Tasks", "Error Logging & Alerts", "Excel/CSV Importers"],
    starterPriceINR: 15000,
    proPriceINR: 35000,
    enterprisePriceINR: 80000,
  },
  {
    id: "srv_salesforce",
    category: "salesforce_data",
    name: "Salesforce CRM Data Entry & Reconciliation",
    description: "Bulk data management, Data Loader inserts, Lead/Account matching, and payment gateway reconciliation.",
    deliverables: ["Data Loader Execution", "200k+ Records Auditing", "Discrepancy Resolution", "Automated Email Reports"],
    starterPriceINR: 20000,
    proPriceINR: 50000,
    enterprisePriceINR: 110000,
  },
  {
    id: "srv_content",
    category: "content_writing",
    name: "Technical Content Writing & SEO Blogs",
    description: "High-authority developer articles, system architecture walkthroughs, and SEO-optimized product documentation.",
    deliverables: ["4x Deep Dive Articles", "Keyword Strategy", "Code Snippets & Diffs", "Social Teasers"],
    starterPriceINR: 12000,
    proPriceINR: 28000,
    enterprisePriceINR: 60000,
  },
  {
    id: "srv_video_ads",
    category: "video_ads",
    name: "Social Media Video Ads & Product Demos",
    description: "High-retention video ads, shorts, and reels with dynamic scripts, viral hooks, subtitles, and voiceover audio.",
    deliverables: ["Script & Storyboard", "Motion Graphics & Visuals", "Voiceover Audio Sync", "Multi-Platform Export"],
    starterPriceINR: 18000,
    proPriceINR: 40000,
    enterprisePriceINR: 90000,
  },
];
