/**
 * VIDA SOTA Agent 4: Deck Builder (PowerPoint Generator)
 * Leverages pptxgenjs to build presentation decks.
 */
import pptxgen from "pptxgenjs";

export interface DeckSlideData {
  title: string;
  subtitle?: string;
  points?: string[];
  metric?: { value: string; label: string };
}

export interface DeckOptions {
  title: string;
  author?: string;
  slides: DeckSlideData[];
}

export class DeckBuilderAgent {
  public async generatePresentation(options: DeckOptions): Promise<Blob> {
    const pres = new pptxgen();

    pres.layout = "LAYOUT_16x9";
    pres.author = options.author || "Nia AI Operating System";
    pres.title = options.title;

    // Title Slide
    const titleSlide = pres.addSlide();
    titleSlide.background = { color: "0B0F19" }; // deep space dark
    titleSlide.addText(options.title, {
      x: 1.0,
      y: 2.2,
      w: "80%",
      h: 1.5,
      fontSize: 36,
      bold: true,
      color: "38BDF8", // Cyan glow
      fontFace: "Segoe UI",
    });
    titleSlide.addText("Generated by Nia AI Companion • SOTA Deck Engine", {
      x: 1.0,
      y: 3.8,
      w: "80%",
      h: 0.8,
      fontSize: 16,
      color: "94A3B8",
      fontFace: "Segoe UI",
    });

    // Content Slides
    options.slides.forEach((s) => {
      const slide = pres.addSlide();
      slide.background = { color: "0F172A" };

      // Header
      slide.addText(s.title, {
        x: 0.8,
        y: 0.6,
        w: "85%",
        h: 0.8,
        fontSize: 26,
        bold: true,
        color: "F8FAFC",
        fontFace: "Segoe UI",
      });

      if (s.subtitle) {
        slide.addText(s.subtitle, {
          x: 0.8,
          y: 1.3,
          w: "85%",
          h: 0.5,
          fontSize: 14,
          color: "38BDF8",
          fontFace: "Segoe UI",
        });
      }

      // Bullet Points
      if (s.points && s.points.length > 0) {
        const textItems = s.points.map((pt) => ({
          text: pt,
          options: { fontSize: 15, color: "E2E8F0", breakLine: true, bullet: true, fontFace: "Segoe UI" },
        }));
        slide.addText(textItems as any, {
          x: 0.8,
          y: 2.0,
          w: s.metric ? "55%" : "85%",
          h: 4.0,
          margin: 0.1,
        });
      }

      // Metric Highlight Box
      if (s.metric) {
        slide.addShape(pres.ShapeType.rect, {
          x: 7.2,
          y: 2.2,
          w: 2.5,
          h: 2.2,
          fill: { color: "1E293B" },
          line: { color: "38BDF8", width: 1.5 },
        });
        slide.addText(s.metric.value, {
          x: 7.2,
          y: 2.5,
          w: 2.5,
          h: 0.8,
          fontSize: 32,
          bold: true,
          color: "38BDF8",
          align: "center",
          fontFace: "Segoe UI",
        });
        slide.addText(s.metric.label, {
          x: 7.2,
          y: 3.3,
          w: 2.5,
          h: 0.8,
          fontSize: 13,
          color: "94A3B8",
          align: "center",
          fontFace: "Segoe UI",
        });
      }
    });

    const output = await pres.write({ outputType: "blob" });
    return output as Blob;
  }
}

export const deckBuilder = new DeckBuilderAgent();
