import { EvidenceItem } from "./types";

/**
 * MASTER EVIDENCE DATABASE FOR VISHWAJEET
 *
 * Source of truth for all 8 resume variants, claims, metrics, projects, and work history.
 * Verified against BCA mark sheets, Diploma certificates, LinkedIn, and GitHub repos.
 */

export const VISHWAJEET_CONTACT_INFO = {
  name: "VISHWAJEET",
  title: "AI Software Engineer | Full Stack Developer",
  location: "Bengaluru, Karnataka, India",
  phone: "+91 85952 02922",
  email: "vishwajeetsrk@gmail.com",
  linkedin: "https://linkedin.com/in/Vishwajeetsrk",
  github: "https://github.com/Vishwajeetsrk",
  portfolio: "https://vishwajeetsrk.github.io",
  liveProjects: ["https://learnifyai.in", "http://localhost:3000"],
};

export const MASTER_EVIDENCE_GRAPH: EvidenceItem[] = [
  // 1. Professional Experiences
  {
    id: "ev_exp_rootbridge_reconcile",
    category: "experience",
    title: "Reconciliation & Data Management Specialist",
    description: "Processed and maintained 200,000+ records across operational reconciliation and data-management workflows. Resolved 50+ recurring data mismatches monthly through structured validation. Improved reported data accuracy by 30%. Worked with Excel, Salesforce CRM, and Salesforce Data Loader.",
    source: "Rootbridge Academy Pvt. Ltd. Employment Record",
    verified: true,
    confidence: 1.0,
    date: "Dec 2024–Present",
    tags: ["salesforce", "data-loader", "reconciliation", "crm", "excel", "data-integrity"],
    skills: ["Salesforce CRM", "Salesforce Data Loader", "Excel", "Data Validation", "Data Reconciliation", "Data Quality"],
    metrics: {
      recordsProcessed: "200,000+ records processed and maintained",
      monthlyFixes: "50+ recurring data mismatches resolved monthly",
      accuracyImprovement: "30% improvement in reported data accuracy",
    },
    allowedOnResume: true,
  },
  {
    id: "ev_exp_unacademy",
    category: "experience",
    title: "Social Media & Automation Intern",
    description: "Managed educational content workflows and optimized digital content metadata. Improved workflow efficiency using Python-based automation.",
    source: "Sorting Hat Technologies / Unacademy Internship Record",
    verified: true,
    confidence: 1.0,
    date: "Feb–Mar 2026",
    tags: ["python", "automation", "content-workflows", "metadata"],
    skills: ["Python", "Content Automation", "Metadata Optimization", "Workflow Efficiency"],
    allowedOnResume: true,
  },
  {
    id: "ev_exp_viewmyrecords",
    category: "experience",
    title: "Employee Data Network Uploader",
    description: "Uploaded and managed employee records in company database systems. Supported structured employee-data processing and record management.",
    source: "ViewMyRecords Pvt. Ltd. Employment Record",
    verified: true,
    confidence: 1.0,
    date: "Jan–Apr 2023",
    tags: ["database", "employee-records", "data-entry", "record-management"],
    skills: ["Data Management", "Record Uploading", "Database Systems"],
    allowedOnResume: true,
  },
  {
    id: "ev_exp_rootbridge_fundraiser",
    category: "experience",
    title: "Fundraiser",
    description: "Built stakeholder relationships and supported fundraising and outreach activities.",
    source: "Rootbridge Academy Employment Record",
    verified: true,
    confidence: 0.95,
    date: "Apr–Nov 2024 [VERIFY DATE]",
    dateWarning: "[VERIFY DATE]",
    tags: ["fundraising", "stakeholder-relations", "outreach"],
    skills: ["Stakeholder Relations", "Fundraising", "Communication"],
    allowedOnResume: true,
  },

  // 2. Core Projects
  {
    id: "ev_proj_learnify",
    category: "project",
    title: "Learnify AI — AI Learning & Career Platform",
    description: "Full-stack AI-powered learning and career platform with AI tutoring, career guidance, creator toolkits, gamification, and community functionality. Integrated LLM capabilities using OpenRouter and backend services through Supabase.",
    source: "Production Web App: learnifyai.in / GitHub",
    verified: true,
    confidence: 1.0,
    date: "May 2026–Present",
    tags: ["react19", "typescript", "supabase", "openrouter", "cashfree", "tailwind"],
    skills: ["React 19", "TypeScript", "Supabase", "OpenRouter", "Cashfree", "Tailwind CSS", "LLM APIs"],
    allowedOnResume: true,
  },
  {
    id: "ev_proj_dreamsync",
    category: "project",
    title: "DreamSync — AI Career Intelligence Platform",
    description: "Built AI Resume Builder, ATS Checker, LinkedIn Optimizer, and Portfolio Generator. Developed responsive AI-powered career workflows with Gemini and Upstash Redis.",
    source: "Production Web App / GitHub Repo",
    verified: true,
    confidence: 1.0,
    date: "Feb–Apr 2026",
    tags: ["nextjs", "react", "firebase", "openrouter", "gemini", "redis", "tailwind"],
    skills: ["Next.js", "React", "Firebase", "OpenRouter", "Gemini", "Upstash Redis", "ATS Checker", "Resume Optimization"],
    allowedOnResume: true,
  },
  {
    id: "ev_proj_luxurylaundry",
    category: "project",
    title: "Luxury Laundry — SaaS Platform",
    description: "Developed customer and admin dashboards, database architecture with PostgreSQL/Prisma, and real-time SaaS functionality using Socket.io.",
    source: "Production SaaS App / GitHub Repo",
    verified: true,
    confidence: 1.0,
    date: "Apr–May 2026",
    tags: ["nextjs", "express", "postgresql", "prisma", "socketio", "tailwind"],
    skills: ["Next.js", "Express.js", "PostgreSQL", "Prisma", "Socket.io", "Realtime Dashboards"],
    allowedOnResume: true,
  },
  {
    id: "ev_proj_jarvis",
    category: "project",
    title: "JARVIS AI OS — Autonomous Agent Operating System",
    description: "Constructed 18 specialized agent personas over a unified Task Runtime, 3D WebGL particle constellation (Three.js), and multi-tier vector context engine.",
    source: "GitHub: Vishwajeetsrk/JARVIS-AI-OS",
    verified: true,
    confidence: 1.0,
    tags: ["react19", "nextjs15", "threejs", "webgl", "supabase", "typescript"],
    skills: ["Three.js", "WebGL", "React 19", "Next.js 15", "Agentic Architecture", "System Design"],
    metrics: {
      personas: "18 specialized AI personas",
      frameRate: "60 FPS hardware-accelerated 3D rendering",
    },
    allowedOnResume: true,
  },

  // 3. Education & Academic Excellence
  {
    id: "ev_edu_bca",
    category: "education",
    title: "Bachelor of Computer Applications (BCA)",
    description: "St. Aloysius Degree College, Bengaluru. CGPA 8.1/10 | Final Semester SGPA 9.06/10 | 89.57% (627/700) | First Class Exemplary | 148/150 Project Work | 99/100 Internship.",
    source: "St. Aloysius College / Bangalore University Official Mark Card",
    verified: true,
    confidence: 1.0,
    date: "Jul 2023–Jul 2026",
    tags: ["bca", "degree", "first-class-exemplary", "high-cgpa"],
    skills: ["Computer Science", "Data Structures", "Database Management", "Web Engineering", "Data Science Fundamentals"],
    metrics: {
      cgpa: "8.1/10 CGPA",
      finalSgpa: "9.06/10 Final SGPA",
      percentage: "89.57% (627/700) First Class Exemplary",
      projectScore: "148/150 Project Work",
      internshipScore: "99/100 Internship",
    },
    allowedOnResume: true,
  },
  {
    id: "ev_edu_diploma",
    category: "education",
    title: "Diploma in Software Development",
    description: "Oxford Software Institute. Grade A certification in full-stack software development, JavaScript, Python, and SQL.",
    source: "Oxford Software Institute Official Certificate",
    verified: true,
    confidence: 1.0,
    date: "Feb 2021–Feb 2022",
    tags: ["diploma", "software-development", "grade-a"],
    skills: ["Full Stack Development", "JavaScript", "Python", "SQL", "Database Systems"],
    allowedOnResume: true,
  },

  // 4. Certifications & Honors
  {
    id: "ev_cert_github_copilot",
    category: "certification",
    title: "AI Pair Programming with GitHub Copilot",
    description: "Official LinkedIn Learning Certificate in AI-assisted code generation, testing, and refactoring.",
    source: "LinkedIn Learning Certificate",
    verified: true,
    confidence: 1.0,
    tags: ["copilot", "ai-programming", "linkedin"],
    skills: ["GitHub Copilot", "AI Pair Programming", "Productivity"],
    allowedOnResume: true,
  },
  {
    id: "ev_cert_tata_genai",
    category: "certification",
    title: "Tata GenAI Powered Data Analytics",
    description: "Forage Job Simulation certificate in Generative AI data analysis, reporting, and predictive modeling.",
    source: "Forage Official Certificate",
    verified: true,
    confidence: 1.0,
    tags: ["genai", "data-analytics", "forage", "tata"],
    skills: ["Generative AI", "Data Analytics", "Predictive Modeling"],
    allowedOnResume: true,
  },
  {
    id: "ev_cert_power_bi",
    category: "certification",
    title: "Power BI for Data Analysts",
    description: "LinkedIn Learning Certificate in business intelligence dashboards, DAX queries, and ETL pipelines.",
    source: "LinkedIn Learning Certificate",
    verified: true,
    confidence: 1.0,
    tags: ["power-bi", "business-intelligence", "data-visualization"],
    skills: ["Power BI", "DAX", "Data Modeling", "Business Intelligence"],
    allowedOnResume: true,
  },
  {
    id: "ev_cert_excel_greatlearning",
    category: "certification",
    title: "Microsoft Excel & Data Analysis",
    description: "Great Learning Certificate in advanced Excel functions, VLOOKUP/XLOOKUP, and pivot tables.",
    source: "Great Learning Certificate",
    verified: true,
    confidence: 1.0,
    tags: ["excel", "data-analysis", "great-learning"],
    skills: ["Microsoft Excel", "Data Cleaning", "Pivot Tables"],
    allowedOnResume: true,
  },
  {
    id: "ev_cert_googlesheets",
    category: "certification",
    title: "Google Sheets for Analytics",
    description: "Simplilearn Certificate in Google Sheets formula automation and collaborative data reporting.",
    source: "Simplilearn Certificate",
    verified: true,
    confidence: 1.0,
    tags: ["google-sheets", "analytics", "simplilearn"],
    skills: ["Google Sheets", "ETL", "Reporting"],
    allowedOnResume: true,
  },
  {
    id: "ev_cert_mysql",
    category: "certification",
    title: "MySQL Basics & Relational Queries",
    description: "Great Learning Certificate in SQL schema design, joins, subqueries, and indexing.",
    source: "Great Learning Certificate",
    verified: true,
    confidence: 1.0,
    tags: ["mysql", "sql", "great-learning"],
    skills: ["MySQL", "Relational Database", "SQL Queries"],
    allowedOnResume: true,
  },
  {
    id: "ev_award_neuro2026",
    category: "achievement",
    title: "1st Prize — NEURO2026 Web Design Competition",
    description: "Won First Prize in prestigious inter-college NEURO2026 Web Design Competition for outstanding UI/UX, responsive architecture, and creative visual engineering.",
    source: "NEURO2026 Web Design Championship Trophy/Certificate",
    verified: true,
    confidence: 1.0,
    tags: ["award", "1st-prize", "web-design", "neuro2026"],
    skills: ["Web Design", "Creative UI/UX", "Frontend Architecture", "Visual Polish"],
    allowedOnResume: true,
  },
];
