/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDesignSystemsRouteImport } from './routes/api/design-systems'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiVisionRouteImport } from './routes/api/vision'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console/index'
import { Route as AuthenticatedConsoleThreadIdRouteImport } from './routes/_authenticated/console/$threadId'
import { Route as AuthenticatedConsoleConnectorsRouteImport } from './routes/_authenticated/console/connectors'
import { Route as AuthenticatedConsoleDesignRouteImport } from './routes/_authenticated/console/design'
import { Route as AuthenticatedConsoleGithubRouteImport } from './routes/_authenticated/console/github'
import { Route as AuthenticatedConsolePluginsRouteImport } from './routes/_authenticated/console/plugins'
import { Route as AuthenticatedConsoleSettingsRouteImport } from './routes/_authenticated/console/settings'
import { Route as AuthenticatedConsoleSkillsRouteImport } from './routes/_authenticated/console/skills'
import { Route as AuthenticatedConsoleTemplatesRouteImport } from './routes/_authenticated/console/templates'
import { Route as AuthenticatedConsoleToolsRouteImport } from './routes/_authenticated/console/tools'
import { Route as ApiDesktopScreenshotRouteImport } from './routes/api/desktop/screenshot'
import { Route as ApiDesktopSystemRouteImport } from './routes/api/desktop/system'
import { Route as AuthenticatedConsoleDesignSystemIdRouteImport } from './routes/_authenticated/console/design.$systemId'
import { Route as AuthenticatedConsoleProjectsProjectIdRouteImport } from './routes/_authenticated/console/projects.$projectId'
import { Route as AuthenticatedConsoleTemplatesSystemIdRouteImport } from './routes/_authenticated/console/templates.$systemId'
import { Route as ApiDesignSystemsIdPreviewRouteImport } from './routes/api/design-systems/$id/preview'
import { Route as ApiDesignSystemsIdTemplatesRouteImport } from './routes/api/design-systems/$id/templates'
import { Route as ApiDesignSystemsIdTemplatesFileRouteImport } from './routes/api/design-systems/$id/templates/$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignSystemsRoute = ApiDesignSystemsRouteImport.update({
  id: '/api/design-systems',
  path: '/api/design-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionRoute = ApiVisionRouteImport.update({
  id: '/api/vision',
  path: '/api/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleThreadIdRoute =
  AuthenticatedConsoleThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleConnectorsRoute =
  AuthenticatedConsoleConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleDesignRoute =
  AuthenticatedConsoleDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleGithubRoute =
  AuthenticatedConsoleGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsolePluginsRoute =
  AuthenticatedConsolePluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSettingsRoute =
  AuthenticatedConsoleSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSkillsRoute =
  AuthenticatedConsoleSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleTemplatesRoute =
  AuthenticatedConsoleTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleToolsRoute =
  AuthenticatedConsoleToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const ApiDesktopScreenshotRoute = ApiDesktopScreenshotRouteImport.update({
  id: '/api/desktop/screenshot',
  path: '/api/desktop/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopSystemRoute = ApiDesktopSystemRouteImport.update({
  id: '/api/desktop/system',
  path: '/api/desktop/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleDesignSystemIdRoute =
  AuthenticatedConsoleDesignSystemIdRouteImport.update({
    id: '/$systemId',
    path: '/$systemId',
    getParentRoute: () => AuthenticatedConsoleDesignRoute,
  } as any)
const AuthenticatedConsoleProjectsProjectIdRoute =
  AuthenticatedConsoleProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleTemplatesSystemIdRoute =
  AuthenticatedConsoleTemplatesSystemIdRouteImport.update({
    id: '/$systemId',
    path: '/$systemId',
    getParentRoute: () => AuthenticatedConsoleTemplatesRoute,
  } as any)
const ApiDesignSystemsIdPreviewRoute =
  ApiDesignSystemsIdPreviewRouteImport.update({
    id: '/$id/preview',
    path: '/$id/preview',
    getParentRoute: () => ApiDesignSystemsRoute,
  } as any)
const ApiDesignSystemsIdTemplatesRoute =
  ApiDesignSystemsIdTemplatesRouteImport.update({
    id: '/$id/templates',
    path: '/$id/templates',
    getParentRoute: () => ApiDesignSystemsRoute,
  } as any)
const ApiDesignSystemsIdTemplatesFileRoute =
  ApiDesignSystemsIdTemplatesFileRouteImport.update({
    id: '/$file',
    path: '/$file',
    getParentRoute: () => ApiDesignSystemsIdTemplatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/design-systems': typeof ApiDesignSystemsRouteWithChildren
  '/api/news': typeof ApiNewsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/vision': typeof ApiVisionRoute
  '/console/$threadId': typeof AuthenticatedConsoleThreadIdRoute
  '/console/connectors': typeof AuthenticatedConsoleConnectorsRoute
  '/console/design': typeof AuthenticatedConsoleDesignRouteWithChildren
  '/console/github': typeof AuthenticatedConsoleGithubRoute
  '/console/plugins': typeof AuthenticatedConsolePluginsRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/skills': typeof AuthenticatedConsoleSkillsRoute
  '/console/templates': typeof AuthenticatedConsoleTemplatesRouteWithChildren
  '/console/tools': typeof AuthenticatedConsoleToolsRoute
  '/api/desktop/screenshot': typeof ApiDesktopScreenshotRoute
  '/api/desktop/system': typeof ApiDesktopSystemRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/console/design/$systemId': typeof AuthenticatedConsoleDesignSystemIdRoute
  '/console/projects/$projectId': typeof AuthenticatedConsoleProjectsProjectIdRoute
  '/console/templates/$systemId': typeof AuthenticatedConsoleTemplatesSystemIdRoute
  '/api/design-systems/$id/preview': typeof ApiDesignSystemsIdPreviewRoute
  '/api/design-systems/$id/templates': typeof ApiDesignSystemsIdTemplatesRouteWithChildren
  '/api/design-systems/$id/templates/$file': typeof ApiDesignSystemsIdTemplatesFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/design-systems': typeof ApiDesignSystemsRouteWithChildren
  '/api/news': typeof ApiNewsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/vision': typeof ApiVisionRoute
  '/console/$threadId': typeof AuthenticatedConsoleThreadIdRoute
  '/console/connectors': typeof AuthenticatedConsoleConnectorsRoute
  '/console/design': typeof AuthenticatedConsoleDesignRouteWithChildren
  '/console/github': typeof AuthenticatedConsoleGithubRoute
  '/console/plugins': typeof AuthenticatedConsolePluginsRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/skills': typeof AuthenticatedConsoleSkillsRoute
  '/console/templates': typeof AuthenticatedConsoleTemplatesRouteWithChildren
  '/console/tools': typeof AuthenticatedConsoleToolsRoute
  '/api/desktop/screenshot': typeof ApiDesktopScreenshotRoute
  '/api/desktop/system': typeof ApiDesktopSystemRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/console/design/$systemId': typeof AuthenticatedConsoleDesignSystemIdRoute
  '/console/projects/$projectId': typeof AuthenticatedConsoleProjectsProjectIdRoute
  '/console/templates/$systemId': typeof AuthenticatedConsoleTemplatesSystemIdRoute
  '/api/design-systems/$id/preview': typeof ApiDesignSystemsIdPreviewRoute
  '/api/design-systems/$id/templates': typeof ApiDesignSystemsIdTemplatesRouteWithChildren
  '/api/design-systems/$id/templates/$file': typeof ApiDesignSystemsIdTemplatesFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/design-systems': typeof ApiDesignSystemsRouteWithChildren
  '/api/news': typeof ApiNewsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/vision': typeof ApiVisionRoute
  '/_authenticated/console/$threadId': typeof AuthenticatedConsoleThreadIdRoute
  '/_authenticated/console/connectors': typeof AuthenticatedConsoleConnectorsRoute
  '/_authenticated/console/design': typeof AuthenticatedConsoleDesignRouteWithChildren
  '/_authenticated/console/github': typeof AuthenticatedConsoleGithubRoute
  '/_authenticated/console/plugins': typeof AuthenticatedConsolePluginsRoute
  '/_authenticated/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/_authenticated/console/skills': typeof AuthenticatedConsoleSkillsRoute
  '/_authenticated/console/templates': typeof AuthenticatedConsoleTemplatesRouteWithChildren
  '/_authenticated/console/tools': typeof AuthenticatedConsoleToolsRoute
  '/api/desktop/screenshot': typeof ApiDesktopScreenshotRoute
  '/api/desktop/system': typeof ApiDesktopSystemRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/console/design/$systemId': typeof AuthenticatedConsoleDesignSystemIdRoute
  '/_authenticated/console/projects/$projectId': typeof AuthenticatedConsoleProjectsProjectIdRoute
  '/_authenticated/console/templates/$systemId': typeof AuthenticatedConsoleTemplatesSystemIdRoute
  '/api/design-systems/$id/preview': typeof ApiDesignSystemsIdPreviewRoute
  '/api/design-systems/$id/templates': typeof ApiDesignSystemsIdTemplatesRouteWithChildren
  '/api/design-systems/$id/templates/$file': typeof ApiDesignSystemsIdTemplatesFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/projects'
    | '/skills'
    | '/console'
    | '/api/chat'
    | '/api/design-systems'
    | '/api/news'
    | '/api/sitemap'
    | '/api/speak'
    | '/api/transcribe'
    | '/api/vision'
    | '/console/$threadId'
    | '/console/connectors'
    | '/console/design'
    | '/console/github'
    | '/console/plugins'
    | '/console/settings'
    | '/console/skills'
    | '/console/templates'
    | '/console/tools'
    | '/api/desktop/screenshot'
    | '/api/desktop/system'
    | '/console/'
    | '/console/design/$systemId'
    | '/console/projects/$projectId'
    | '/console/templates/$systemId'
    | '/api/design-systems/$id/preview'
    | '/api/design-systems/$id/templates'
    | '/api/design-systems/$id/templates/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/projects'
    | '/skills'
    | '/api/chat'
    | '/api/design-systems'
    | '/api/news'
    | '/api/sitemap'
    | '/api/speak'
    | '/api/transcribe'
    | '/api/vision'
    | '/console/$threadId'
    | '/console/connectors'
    | '/console/design'
    | '/console/github'
    | '/console/plugins'
    | '/console/settings'
    | '/console/skills'
    | '/console/templates'
    | '/console/tools'
    | '/api/desktop/screenshot'
    | '/api/desktop/system'
    | '/console'
    | '/console/design/$systemId'
    | '/console/projects/$projectId'
    | '/console/templates/$systemId'
    | '/api/design-systems/$id/preview'
    | '/api/design-systems/$id/templates'
    | '/api/design-systems/$id/templates/$file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/how-it-works'
    | '/projects'
    | '/skills'
    | '/_authenticated/console'
    | '/api/chat'
    | '/api/design-systems'
    | '/api/news'
    | '/api/sitemap'
    | '/api/speak'
    | '/api/transcribe'
    | '/api/vision'
    | '/_authenticated/console/$threadId'
    | '/_authenticated/console/connectors'
    | '/_authenticated/console/design'
    | '/_authenticated/console/github'
    | '/_authenticated/console/plugins'
    | '/_authenticated/console/settings'
    | '/_authenticated/console/skills'
    | '/_authenticated/console/templates'
    | '/_authenticated/console/tools'
    | '/api/desktop/screenshot'
    | '/api/desktop/system'
    | '/_authenticated/console/'
    | '/_authenticated/console/design/$systemId'
    | '/_authenticated/console/projects/$projectId'
    | '/_authenticated/console/templates/$systemId'
    | '/api/design-systems/$id/preview'
    | '/api/design-systems/$id/templates'
    | '/api/design-systems/$id/templates/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ProjectsRoute: typeof ProjectsRoute
  SkillsRoute: typeof SkillsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDesignSystemsRoute: typeof ApiDesignSystemsRouteWithChildren
  ApiNewsRoute: typeof ApiNewsRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiVisionRoute: typeof ApiVisionRoute
  ApiDesktopScreenshotRoute: typeof ApiDesktopScreenshotRoute
  ApiDesktopSystemRoute: typeof ApiDesktopSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/design-systems': {
      id: '/api/design-systems'
      path: '/api/design-systems'
      fullPath: '/api/design-systems'
      preLoaderRoute: typeof ApiDesignSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision': {
      id: '/api/vision'
      path: '/api/vision'
      fullPath: '/api/vision'
      preLoaderRoute: typeof ApiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/$threadId': {
      id: '/_authenticated/console/$threadId'
      path: '/$threadId'
      fullPath: '/console/$threadId'
      preLoaderRoute: typeof AuthenticatedConsoleThreadIdRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/connectors': {
      id: '/_authenticated/console/connectors'
      path: '/connectors'
      fullPath: '/console/connectors'
      preLoaderRoute: typeof AuthenticatedConsoleConnectorsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/design': {
      id: '/_authenticated/console/design'
      path: '/design'
      fullPath: '/console/design'
      preLoaderRoute: typeof AuthenticatedConsoleDesignRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/github': {
      id: '/_authenticated/console/github'
      path: '/github'
      fullPath: '/console/github'
      preLoaderRoute: typeof AuthenticatedConsoleGithubRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/plugins': {
      id: '/_authenticated/console/plugins'
      path: '/plugins'
      fullPath: '/console/plugins'
      preLoaderRoute: typeof AuthenticatedConsolePluginsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/settings': {
      id: '/_authenticated/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof AuthenticatedConsoleSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/skills': {
      id: '/_authenticated/console/skills'
      path: '/skills'
      fullPath: '/console/skills'
      preLoaderRoute: typeof AuthenticatedConsoleSkillsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/templates': {
      id: '/_authenticated/console/templates'
      path: '/templates'
      fullPath: '/console/templates'
      preLoaderRoute: typeof AuthenticatedConsoleTemplatesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/tools': {
      id: '/_authenticated/console/tools'
      path: '/tools'
      fullPath: '/console/tools'
      preLoaderRoute: typeof AuthenticatedConsoleToolsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/api/desktop/screenshot': {
      id: '/api/desktop/screenshot'
      path: '/api/desktop/screenshot'
      fullPath: '/api/desktop/screenshot'
      preLoaderRoute: typeof ApiDesktopScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop/system': {
      id: '/api/desktop/system'
      path: '/api/desktop/system'
      fullPath: '/api/desktop/system'
      preLoaderRoute: typeof ApiDesktopSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/design/$systemId': {
      id: '/_authenticated/console/design/$systemId'
      path: '/$systemId'
      fullPath: '/console/design/$systemId'
      preLoaderRoute: typeof AuthenticatedConsoleDesignSystemIdRouteImport
      parentRoute: typeof AuthenticatedConsoleDesignRoute
    }
    '/_authenticated/console/projects/$projectId': {
      id: '/_authenticated/console/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/console/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedConsoleProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/templates/$systemId': {
      id: '/_authenticated/console/templates/$systemId'
      path: '/$systemId'
      fullPath: '/console/templates/$systemId'
      preLoaderRoute: typeof AuthenticatedConsoleTemplatesSystemIdRouteImport
      parentRoute: typeof AuthenticatedConsoleTemplatesRoute
    }
    '/api/design-systems/$id/preview': {
      id: '/api/design-systems/$id/preview'
      path: '/$id/preview'
      fullPath: '/api/design-systems/$id/preview'
      preLoaderRoute: typeof ApiDesignSystemsIdPreviewRouteImport
      parentRoute: typeof ApiDesignSystemsRoute
    }
    '/api/design-systems/$id/templates': {
      id: '/api/design-systems/$id/templates'
      path: '/$id/templates'
      fullPath: '/api/design-systems/$id/templates'
      preLoaderRoute: typeof ApiDesignSystemsIdTemplatesRouteImport
      parentRoute: typeof ApiDesignSystemsRoute
    }
    '/api/design-systems/$id/templates/$file': {
      id: '/api/design-systems/$id/templates/$file'
      path: '/$file'
      fullPath: '/api/design-systems/$id/templates/$file'
      preLoaderRoute: typeof ApiDesignSystemsIdTemplatesFileRouteImport
      parentRoute: typeof ApiDesignSystemsIdTemplatesRoute
    }
  }
}

interface AuthenticatedConsoleDesignRouteChildren {
  AuthenticatedConsoleDesignSystemIdRoute: typeof AuthenticatedConsoleDesignSystemIdRoute
}

const AuthenticatedConsoleDesignRouteChildren: AuthenticatedConsoleDesignRouteChildren =
  {
    AuthenticatedConsoleDesignSystemIdRoute:
      AuthenticatedConsoleDesignSystemIdRoute,
  }

const AuthenticatedConsoleDesignRouteWithChildren =
  AuthenticatedConsoleDesignRoute._addFileChildren(
    AuthenticatedConsoleDesignRouteChildren,
  )

interface AuthenticatedConsoleTemplatesRouteChildren {
  AuthenticatedConsoleTemplatesSystemIdRoute: typeof AuthenticatedConsoleTemplatesSystemIdRoute
}

const AuthenticatedConsoleTemplatesRouteChildren: AuthenticatedConsoleTemplatesRouteChildren =
  {
    AuthenticatedConsoleTemplatesSystemIdRoute:
      AuthenticatedConsoleTemplatesSystemIdRoute,
  }

const AuthenticatedConsoleTemplatesRouteWithChildren =
  AuthenticatedConsoleTemplatesRoute._addFileChildren(
    AuthenticatedConsoleTemplatesRouteChildren,
  )

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleThreadIdRoute: typeof AuthenticatedConsoleThreadIdRoute
  AuthenticatedConsoleConnectorsRoute: typeof AuthenticatedConsoleConnectorsRoute
  AuthenticatedConsoleDesignRoute: typeof AuthenticatedConsoleDesignRouteWithChildren
  AuthenticatedConsoleGithubRoute: typeof AuthenticatedConsoleGithubRoute
  AuthenticatedConsolePluginsRoute: typeof AuthenticatedConsolePluginsRoute
  AuthenticatedConsoleSettingsRoute: typeof AuthenticatedConsoleSettingsRoute
  AuthenticatedConsoleSkillsRoute: typeof AuthenticatedConsoleSkillsRoute
  AuthenticatedConsoleTemplatesRoute: typeof AuthenticatedConsoleTemplatesRouteWithChildren
  AuthenticatedConsoleToolsRoute: typeof AuthenticatedConsoleToolsRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
  AuthenticatedConsoleProjectsProjectIdRoute: typeof AuthenticatedConsoleProjectsProjectIdRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleThreadIdRoute: AuthenticatedConsoleThreadIdRoute,
  AuthenticatedConsoleConnectorsRoute: AuthenticatedConsoleConnectorsRoute,
  AuthenticatedConsoleDesignRoute: AuthenticatedConsoleDesignRouteWithChildren,
  AuthenticatedConsoleGithubRoute: AuthenticatedConsoleGithubRoute,
  AuthenticatedConsolePluginsRoute: AuthenticatedConsolePluginsRoute,
  AuthenticatedConsoleSettingsRoute: AuthenticatedConsoleSettingsRoute,
  AuthenticatedConsoleSkillsRoute: AuthenticatedConsoleSkillsRoute,
  AuthenticatedConsoleTemplatesRoute:
    AuthenticatedConsoleTemplatesRouteWithChildren,
  AuthenticatedConsoleToolsRoute: AuthenticatedConsoleToolsRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
  AuthenticatedConsoleProjectsProjectIdRoute:
    AuthenticatedConsoleProjectsProjectIdRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiDesignSystemsIdTemplatesRouteChildren {
  ApiDesignSystemsIdTemplatesFileRoute: typeof ApiDesignSystemsIdTemplatesFileRoute
}

const ApiDesignSystemsIdTemplatesRouteChildren: ApiDesignSystemsIdTemplatesRouteChildren =
  {
    ApiDesignSystemsIdTemplatesFileRoute: ApiDesignSystemsIdTemplatesFileRoute,
  }

const ApiDesignSystemsIdTemplatesRouteWithChildren =
  ApiDesignSystemsIdTemplatesRoute._addFileChildren(
    ApiDesignSystemsIdTemplatesRouteChildren,
  )

interface ApiDesignSystemsRouteChildren {
  ApiDesignSystemsIdPreviewRoute: typeof ApiDesignSystemsIdPreviewRoute
  ApiDesignSystemsIdTemplatesRoute: typeof ApiDesignSystemsIdTemplatesRouteWithChildren
}

const ApiDesignSystemsRouteChildren: ApiDesignSystemsRouteChildren = {
  ApiDesignSystemsIdPreviewRoute: ApiDesignSystemsIdPreviewRoute,
  ApiDesignSystemsIdTemplatesRoute:
    ApiDesignSystemsIdTemplatesRouteWithChildren,
}

const ApiDesignSystemsRouteWithChildren =
  ApiDesignSystemsRoute._addFileChildren(ApiDesignSystemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  ProjectsRoute: ProjectsRoute,
  SkillsRoute: SkillsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDesignSystemsRoute: ApiDesignSystemsRouteWithChildren,
  ApiNewsRoute: ApiNewsRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiVisionRoute: ApiVisionRoute,
  ApiDesktopScreenshotRoute: ApiDesktopScreenshotRoute,
  ApiDesktopSystemRoute: ApiDesktopSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
